# Generated by Django 5.2.8 on 2026-02-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер исследования')),
                ('people_amounth', models.IntegerField(verbose_name='Количество человек')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haplotype', models.CharField(verbose_name='Название')),
                ('people_amounth', models.IntegerField(verbose_name='Числовое значение')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='data.research', verbose_name='Исследование')),
            ],
        ),
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Локус')),
                ('coef1', models.CharField(max_length=20, verbose_name='Коэффициент 1, есть всегда')),
                ('coef2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Коэффициент2')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loci', to='data.sample')),
            ],
            options={
                'unique_together': {('sample', 'name')},
            },
        ),
    ]
