# Generated by Django 6.0.2 on 2026-02-06 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер исследования')),
                ('people_amount', models.IntegerField(verbose_name='Количество человек')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haplotype', models.CharField(verbose_name='Название')),
                ('people_amount', models.IntegerField(verbose_name='Числовое значение')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='data.research', verbose_name='Исследование')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedHaplotype1k',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_code1k', models.CharField(max_length=50)),
                ('haplotype_str1k', models.CharField(max_length=255)),
                ('people_amount1k', models.PositiveIntegerField(default=0)),
                ('notes1k', models.TextField(blank=True, null=True)),
                ('research1k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_haplotypes1k', to='data.research')),
            ],
            options={
                'ordering': ['research1k', 'format_code1k', 'haplotype_str1k'],
                'unique_together': {('research1k', 'format_code1k', 'haplotype_str1k')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedHaplotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_code', models.CharField(max_length=50)),
                ('haplotype_str', models.CharField(max_length=255)),
                ('people_amount', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_haplotypes', to='data.research')),
            ],
            options={
                'ordering': ['research', 'format_code', 'haplotype_str'],
                'unique_together': {('research', 'format_code', 'haplotype_str')},
            },
        ),
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Локус')),
                ('coef1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Коэффициент 1, есть всегда')),
                ('coef2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Коэффициент2')),
                ('raw_coef', models.CharField(max_length=20, verbose_name='Сырой коэффициент')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loci', to='data.sample')),
            ],
            options={
                'unique_together': {('sample', 'name', 'coef1', 'coef2')},
            },
        ),
    ]
