# Generated by Django 5.2.8 on 2026-02-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locus',
            name='raw_coef',
            field=models.CharField(default=1, max_length=20, verbose_name='Сырой коэффициент'),
            preserve_default=False,
        ),
    ]
