# Generated by Django 5.2.8 on 2026-02-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_locus_raw_coef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locus',
            name='coef1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Коэффициент 1, есть всегда'),
        ),
    ]
