# Generated by Django 5.2.8 on 2026-02-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_locus_coef1'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locus',
            unique_together={('sample', 'name', 'coef1', 'coef2')},
        ),
    ]
