# Generated by Django 6.0.2 on 2026-02-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_locus_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='people_amounth',
            new_name='people_amount',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='people_amounth',
            new_name='people_amount',
        ),
    ]
